### Variables
@baseUrl = http://localhost:3000/api

### 1. Login (Guarda el token automáticamente en una variable)
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "sgauna0@ticketi.com",
  "pass": "12345678"
}

### Extraemos el token devuelto en la respuesta
@token = {{loginRequest.response.body.token}}


### 2. Obtener Usuarios (Usa el token fresco de arriba)
GET {{baseUrl}}/usuarios
Authorization: Bearer {{token}}